### ISSUE TITLE
Merge techs to `stylus`

### ISSUE THREAD

**Issue by blond** [enb-make/enb-stylus#68]
* [x] Add `autoprefixer` option to `css-stylus` tech (#64).
* [x] Remove `css-stylus-with-nib` tech (#65).
* [x] Remove `css-stylus-with-autoprefixer` tech (#66).
* [x] Rename `css-stylus` to `stylus` tech (#67).
